-- Radiology Analytics: External Integrations
USE DATABASE HEALTHCARE_RADIOLOGY;
USE SCHEMA RAW;

-- S3 Stage for radiology data
CREATE OR REPLACE STAGE RADIOLOGY_S3_STAGE
    STORAGE_INTEGRATION = HEALTHCARE_DEMOS_S3_INTEGRATION
    URL = 's3://sg-healthcare-demos-2026/radiology/'
    FILE_FORMAT = (TYPE = 'PARQUET');

-- Bedrock External Access Integration for report extraction
CREATE OR REPLACE NETWORK RULE BEDROCK_RADIOLOGY_RULE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = ('bedrock-runtime.us-west-2.amazonaws.com:443');

CREATE OR REPLACE SECRET BEDROCK_RADIOLOGY_KEY
    TYPE = GENERIC_STRING
    SECRET_STRING = '<REPLACE_WITH_AWS_ACCESS_KEY>';

CREATE OR REPLACE SECRET BEDROCK_RADIOLOGY_SECRET
    TYPE = GENERIC_STRING
    SECRET_STRING = '<REPLACE_WITH_AWS_SECRET_KEY>';

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION BEDROCK_RADIOLOGY_EAI
    ALLOWED_NETWORK_RULES = (BEDROCK_RADIOLOGY_RULE)
    ALLOWED_AUTHENTICATION_SECRETS = (BEDROCK_RADIOLOGY_KEY, BEDROCK_RADIOLOGY_SECRET)
    ENABLED = TRUE;
