-- Radiology Analytics: Curated Dynamic Tables
USE DATABASE HEALTHCARE_RADIOLOGY;
USE SCHEMA CURATED;

CREATE OR REPLACE DYNAMIC TABLE TAT_METRICS
    lag = '5 minutes' refresh_mode = 'AUTO' initialize = 'ON_CREATE' warehouse = CORTEX
AS
SELECT
    s.MODALITY,
    DATE_TRUNC('day', s.STUDY_DATE)::DATE AS METRIC_DATE,
    ROUND(AVG(DATEDIFF(minute, s.STUDY_DATE, r.FINALIZED_AT)), 1) AS AVG_TAT_MINUTES,
    ROUND(MEDIAN(DATEDIFF(minute, s.STUDY_DATE, r.FINALIZED_AT)), 1) AS MEDIAN_TAT_MINUTES,
    COUNT(*) AS STUDIES_COMPLETED,
    SUM(CASE
        WHEN s.MODALITY = 'CT' AND DATEDIFF(minute, s.STUDY_DATE, r.FINALIZED_AT) > 120 THEN 1
        WHEN s.MODALITY = 'MRI' AND DATEDIFF(minute, s.STUDY_DATE, r.FINALIZED_AT) > 180 THEN 1
        WHEN s.MODALITY = 'XR' AND DATEDIFF(minute, s.STUDY_DATE, r.FINALIZED_AT) > 60 THEN 1
        WHEN s.MODALITY = 'US' AND DATEDIFF(minute, s.STUDY_DATE, r.FINALIZED_AT) > 90 THEN 1
        ELSE 0
    END) AS TAT_SLA_BREACH_COUNT,
    ROUND(SUM(CASE
        WHEN s.MODALITY = 'CT' AND DATEDIFF(minute, s.STUDY_DATE, r.FINALIZED_AT) > 120 THEN 1
        WHEN s.MODALITY = 'MRI' AND DATEDIFF(minute, s.STUDY_DATE, r.FINALIZED_AT) > 180 THEN 1
        WHEN s.MODALITY = 'XR' AND DATEDIFF(minute, s.STUDY_DATE, r.FINALIZED_AT) > 60 THEN 1
        WHEN s.MODALITY = 'US' AND DATEDIFF(minute, s.STUDY_DATE, r.FINALIZED_AT) > 90 THEN 1
        ELSE 0
    END) * 100.0 / NULLIF(COUNT(*), 0), 1) AS SLA_BREACH_PCT
FROM HEALTHCARE_RADIOLOGY.RAW.STUDIES s
JOIN HEALTHCARE_RADIOLOGY.RAW.REPORTS r ON s.STUDY_ID = r.STUDY_ID
WHERE r.STATUS = 'FINAL'
GROUP BY s.MODALITY, DATE_TRUNC('day', s.STUDY_DATE)::DATE;

CREATE OR REPLACE DYNAMIC TABLE CRITICAL_FINDINGS_QUEUE
    lag = '5 minutes' refresh_mode = 'AUTO' initialize = 'ON_CREATE' warehouse = CORTEX
AS
SELECT
    cf.FINDING_ID,
    cf.STUDY_ID,
    cf.FINDING_TYPE,
    cf.SEVERITY,
    s.MODALITY,
    s.BODY_PART,
    s.URGENCY,
    r.NAME AS RADIOLOGIST_NAME,
    r.SUBSPECIALTY,
    s.STUDY_DATE,
    DATEDIFF(minute, s.STUDY_DATE, CURRENT_TIMESTAMP()) AS MINUTES_SINCE_DETECTION,
    ROUND(DATEDIFF(minute, s.STUDY_DATE, CURRENT_TIMESTAMP()) / 60.0, 1) AS HOURS_SINCE_DETECTION,
    cf.ACKNOWLEDGED,
    cf.ACKNOWLEDGED_AT,
    cf.COMMUNICATION_METHOD,
    CASE
        WHEN cf.SEVERITY = 'CRITICAL' AND cf.ACKNOWLEDGED = FALSE THEN 1
        WHEN cf.SEVERITY = 'HIGH' AND cf.ACKNOWLEDGED = FALSE THEN 2
        WHEN cf.SEVERITY = 'CRITICAL' AND cf.ACKNOWLEDGED = TRUE THEN 3
        ELSE 4
    END AS PRIORITY_RANK
FROM HEALTHCARE_RADIOLOGY.RAW.CRITICAL_FINDINGS cf
JOIN HEALTHCARE_RADIOLOGY.RAW.STUDIES s ON cf.STUDY_ID = s.STUDY_ID
JOIN HEALTHCARE_RADIOLOGY.RAW.RADIOLOGISTS r ON cf.RADIOLOGIST_ID = r.RADIOLOGIST_ID;

CREATE OR REPLACE DYNAMIC TABLE RADIOLOGIST_PRODUCTIVITY
    lag = '5 minutes' refresh_mode = 'AUTO' initialize = 'ON_CREATE' warehouse = CORTEX
AS
SELECT
    r.RADIOLOGIST_ID,
    r.NAME AS RADIOLOGIST_NAME,
    r.SUBSPECIALTY,
    r.YEARS_EXPERIENCE,
    r.READS_PER_DAY_AVG AS BENCHMARK_READS_PER_DAY,
    DATE_TRUNC('day', rpt.FINALIZED_AT)::DATE AS METRIC_DATE,
    COUNT(*) AS DAILY_READS,
    ROUND(AVG(DATEDIFF(minute, s.STUDY_DATE, rpt.FINALIZED_AT)), 1) AS AVG_TAT_MINUTES,
    SUM(CASE WHEN s.URGENCY = 'STAT' THEN 1 ELSE 0 END) AS STAT_READS,
    SUM(CASE WHEN s.MODALITY = 'CT' THEN 1 ELSE 0 END) AS CT_READS,
    SUM(CASE WHEN s.MODALITY = 'MRI' THEN 1 ELSE 0 END) AS MRI_READS,
    SUM(CASE WHEN s.MODALITY = 'XR' THEN 1 ELSE 0 END) AS XR_READS
FROM HEALTHCARE_RADIOLOGY.RAW.REPORTS rpt
JOIN HEALTHCARE_RADIOLOGY.RAW.STUDIES s ON rpt.STUDY_ID = s.STUDY_ID
JOIN HEALTHCARE_RADIOLOGY.RAW.RADIOLOGISTS r ON rpt.RADIOLOGIST_ID = r.RADIOLOGIST_ID
WHERE rpt.STATUS = 'FINAL'
GROUP BY r.RADIOLOGIST_ID, r.NAME, r.SUBSPECIALTY, r.YEARS_EXPERIENCE, r.READS_PER_DAY_AVG, DATE_TRUNC('day', rpt.FINALIZED_AT)::DATE;
