-- Radiology Analytics: Curated Dynamic Tables
USE DATABASE HEALTHCARE_RADIOLOGY;
USE SCHEMA CURATED;

CREATE OR REPLACE DYNAMIC TABLE TAT_METRICS
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    s.MODALITY,
    DATE(s.ORDER_TIME) AS STUDY_DATE,
    COUNT(*) AS STUDIES_COMPLETED,
    AVG(DATEDIFF(MINUTE, s.ORDER_TIME, s.REPORT_TIME)) AS AVG_TAT_MINUTES,
    MEDIAN(DATEDIFF(MINUTE, s.ORDER_TIME, s.REPORT_TIME)) AS MEDIAN_TAT_MINUTES,
    MAX(DATEDIFF(MINUTE, s.ORDER_TIME, s.REPORT_TIME)) AS MAX_TAT_MINUTES,
    SUM(CASE WHEN DATEDIFF(MINUTE, s.ORDER_TIME, s.REPORT_TIME) >
        CASE s.MODALITY WHEN 'CT' THEN 120 WHEN 'MRI' THEN 180 WHEN 'X-Ray' THEN 60 WHEN 'Ultrasound' THEN 90 ELSE 150 END
        THEN 1 ELSE 0 END) AS TAT_SLA_BREACH_COUNT,
    ROUND(100.0 * SUM(CASE WHEN DATEDIFF(MINUTE, s.ORDER_TIME, s.REPORT_TIME) >
        CASE s.MODALITY WHEN 'CT' THEN 120 WHEN 'MRI' THEN 180 WHEN 'X-Ray' THEN 60 WHEN 'Ultrasound' THEN 90 ELSE 150 END
        THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 1) AS SLA_BREACH_PCT
FROM HEALTHCARE_RADIOLOGY.RAW.STUDIES s
WHERE s.STATUS = 'Completed'
GROUP BY s.MODALITY, DATE(s.ORDER_TIME);

CREATE OR REPLACE DYNAMIC TABLE CRITICAL_FINDINGS_QUEUE
    TARGET_LAG = '5 minutes'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    cf.FINDING_ID,
    cf.STUDY_ID,
    cf.RADIOLOGIST_ID,
    r.FULL_NAME AS RADIOLOGIST_NAME,
    cf.FINDING_TYPE,
    cf.SEVERITY,
    cf.DESCRIPTION,
    cf.IDENTIFIED_AT,
    cf.ACKNOWLEDGED,
    cf.ACKNOWLEDGED_BY,
    cf.ACKNOWLEDGED_AT,
    DATEDIFF(MINUTE, cf.IDENTIFIED_AT, COALESCE(cf.ACKNOWLEDGED_AT, CURRENT_TIMESTAMP())) AS MINUTES_TO_ACKNOWLEDGE,
    CASE
        WHEN cf.SEVERITY = 'Critical' AND NOT cf.ACKNOWLEDGED THEN 1
        WHEN cf.SEVERITY = 'Urgent' AND NOT cf.ACKNOWLEDGED THEN 2
        WHEN cf.SEVERITY = 'High' AND NOT cf.ACKNOWLEDGED THEN 3
        ELSE 4
    END AS PRIORITY_RANK
FROM HEALTHCARE_RADIOLOGY.RAW.CRITICAL_FINDINGS cf
LEFT JOIN HEALTHCARE_RADIOLOGY.RAW.RADIOLOGISTS r ON cf.RADIOLOGIST_ID = r.RADIOLOGIST_ID;

CREATE OR REPLACE DYNAMIC TABLE RADIOLOGIST_PRODUCTIVITY
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    r.RADIOLOGIST_ID,
    r.FULL_NAME,
    r.SUBSPECIALTY,
    r.SHIFT,
    r.DAILY_TARGET,
    DATE(s.REPORT_TIME) AS REPORT_DATE,
    COUNT(*) AS DAILY_READS,
    AVG(DATEDIFF(MINUTE, s.ORDER_TIME, s.REPORT_TIME)) AS AVG_TAT_MINUTES,
    SUM(CASE WHEN s.PRIORITY = 'STAT' THEN 1 ELSE 0 END) AS STAT_READS,
    ROUND(100.0 * COUNT(*) / NULLIF(r.DAILY_TARGET, 0), 1) AS TARGET_ACHIEVEMENT_PCT
FROM HEALTHCARE_RADIOLOGY.RAW.STUDIES s
JOIN HEALTHCARE_RADIOLOGY.RAW.RADIOLOGISTS r ON s.RADIOLOGIST_ID = r.RADIOLOGIST_ID
WHERE s.STATUS = 'Completed'
GROUP BY r.RADIOLOGIST_ID, r.FULL_NAME, r.SUBSPECIALTY, r.SHIFT, r.DAILY_TARGET, DATE(s.REPORT_TIME);
