-- Radiology Analytics: Cortex Search
USE DATABASE HEALTHCARE_RADIOLOGY;
USE SCHEMA SEARCH;

CREATE OR REPLACE CORTEX SEARCH SERVICE GUIDELINES_SEARCH
    ON HEALTHCARE_RADIOLOGY.RAW.RADIOLOGY_GUIDELINES
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
    ATTRIBUTES CATEGORY, TITLE
    AS (
        SELECT
            GUIDELINE_ID,
            TITLE,
            CATEGORY,
            CONTENT,
            EFFECTIVE_DATE,
            VERSION
        FROM HEALTHCARE_RADIOLOGY.RAW.RADIOLOGY_GUIDELINES
    );
