-- Radiology Analytics: ML Models (Forecast + Anomaly Detection)
USE DATABASE HEALTHCARE_RADIOLOGY;
USE SCHEMA ML;

CREATE OR REPLACE VIEW TAT_FORECAST_INPUT AS
SELECT
    MODALITY,
    STUDY_DATE AS DS,
    AVG_TAT_MINUTES AS Y
FROM HEALTHCARE_RADIOLOGY.CURATED.TAT_METRICS
WHERE STUDY_DATE < CURRENT_DATE();

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST TAT_FORECAST_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'TAT_FORECAST_INPUT'),
    SERIES_COLNAME => 'MODALITY',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y'
);

CALL TAT_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 30);

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION TAT_ANOMALY_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'TAT_FORECAST_INPUT'),
    SERIES_COLNAME => 'MODALITY',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y'
);

CALL TAT_ANOMALY_MODEL!DETECT_ANOMALIES(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'TAT_FORECAST_INPUT'),
    SERIES_COLNAME => 'MODALITY',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y'
);
